name: dpok
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch=2.3.0
  - torchvision=0.18.0
  - torchaudio=2.3.0
  - pytorch-cuda=11.8
  - pip
  - pip:
    - accelerate==0.17.0
    - diffusers==0.14.0
    - opencv-python
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - tensorboard
    - transformers
    - kornia
    - fairscale
    - importlib-metadata
    - timm
    - datasets
    - huggingface_hub==0.14.1
    - absl-py>=0.12.0
    - jax==0.4.7
    - jaxlib==0.4.7
    - lingvo==0.12.6
    - paxml==1.0.0
    - scipy==1.12.0
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
